spring.application.name=enotes API

spring.datasource.url=jdbc:postgresql://localhost:5432/enotes
spring.datasource.username=postgres
spring.datasource.password=1026344372
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

